name: website
description: The website of Flutter NL
publish_to: 'none'
version: 1.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  font_awesome_flutter: ^9.0.0
  url_launcher: ^5.7.10
  google_fonts: ^2.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/flutternl_background.png
    - images/flutternl_foreground.png
    - images/
